version: 2
jobs:
  release:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: semantic-release
          command: |
            if git log --format=%B -n 1 | grep -E '.*\[skip semantic-release\].*' >/dev/null; then
              echo "[skip semantic-release]を含むのでskipします。"
            else
              echo "[skip semantic-release]を含まないのでsemantic-releaseを実行します。"
              npm i
              npx semantic-release --debug
            fi

workflows:
  version: 2
  test_and_release:
    jobs:
      - release:
          filters:
            branches:
              only: /^release\/v.*/

